### ISSUE TITLE
Lỗi không viết được 2 dấu trong 1 từ

### ISSUE THREAD

**Issue by s5k** [jokey-im/jokey#10]
Hi,

Mình dùng Skype, thỉnh thoảng viết dấu trên 1 từ thì bị lỗi.

Vd: mình muốn viết chữ "Thấy", thì sẽ bị lỗi thành "tháy", và sau đó các từ khác bị tương tự, mình có thử bỏ 'Không gạch ngang' lên thì viết được.

**Comment by s5k** [comment]
Đây là lúc mình bật 'Không gạch chân' thì bị lỗi
![Screen Shot 2022-12-05 at 12 24 30](https://user-images.githubusercontent.com/40916972/205555926-61080344-2a0a-430d-aae9-035ef36c7da0.png)

**Comment by openhoangnc** [comment]
có thể là skype tự động sửa lỗi chính tả, bạn thử tắt auto correction nhé
- https://www.businessinsider.com/guides/tech/how-to-turn-off-autocorrect-on-mac
