### ISSUE TITLE
Không chuyển đổi được Input Source bằng phím Fn (🌐 )

### ISSUE THREAD

**Issue by brianpham93** [jokey-im/jokey#11]
Version: v0.2.22-c
macOS: 13.1

Không chuyển đổi được Input Source bằng phím Fn (🌐 )
Keyboard setting đã set đúng shortcut

<img width="482" alt="CleanShot 2023-01-09 at 23 25 42@2x" src="https://user-images.githubusercontent.com/6511700/211344144-5c6b69ce-8df5-4234-b8e6-39bc7684eb89.png">

**Comment by openhoangnc** [comment]
Bạn kiểm tra setting này nữa nhé, và cho mình bàn phím của bạn có phải layout US không
![image](https://user-images.githubusercontent.com/20717116/218029588-1056806f-6593-49c9-9afd-d7cc9b7ee025.png)

![image](https://user-images.githubusercontent.com/20717116/218029490-7bdbcaf0-b5d7-4d65-af7d-0d6c356c7745.png)

**Comment by openhoangnc** [comment]
nếu bạn vẫn còn gặp vấn đề thì hãy mở lại (hoặc tạo issue mới)
