### ISSUE TITLE
Lỗi nhập trong illustrator

### ISSUE THREAD

**Issue by phungtham** [jokey-im/jokey#12]
Ở những phiên bản cũ từ 0.2.21 mình thấy nhập liệu trên illustrator khá ngon so với các phần mềm gõ tiếng việt khác. Rất ít lỗi khi nhập liệu nhanh. Nhưng từ phiên bản 0.2.22 trở đi thì nhập liệu nhanh là chữ nhảy tùm lum, lúc mất chữ, lúc nhảy chữ.

**Comment by openhoangnc** [comment]
hi @phungtham, bạn thử v0.2.23-a xem có còn lỗi này không

`curl -sS https://afixer.app/jokey/install.sh | V=0.2.23-a sh`

**Comment by phungtham** [comment]
> hi @phungtham, bạn thử v0.2.23-a xem có còn lỗi này không
> 
> `curl -sS https://afixer.app/jokey/install.sh | V=0.2.23-a sh`



> hi @phungtham, bạn thử v0.2.23-a xem có còn lỗi này không
> 
> `curl -sS https://afixer.app/jokey/install.sh | V=0.2.23-a sh`

Hi bạn. Mình mới lên 0.2.23 dường như lỗi nặng hơn với illustrator. Bản chất phần mềm adobe illustrator này khá khác biệt với các phần mềm khác thì phải. Mình đã cài nhiều phần mềm gõ và sau khi được giới thiệu tới JOKey thì vấn đề đã được tháo gỡ. Hi vọng, phiên bản 0.2.23 này sớm khắc phục được lỗi trên như phiên bản trước. Xin cảm ơn!

**Comment by openhoangnc** [comment]
@phungtham bạn thử v0.2.23-b giúp mình, bản này mình lấy lại một số xử lý từ v0.2.21 cho các app của adobe

```sh
curl -sS https://afixer.app/jokey/install.sh | V=0.2.23-b sh
```
