### ISSUE TITLE
Lỗi tự động chuyển về kiểu gõ telex sau khi khởi động lại

### ISSUE THREAD

**Issue by toandpham** [jokey-im/jokey#13]
Mình là người dùng sử dụng kiểu gõ VNI tuy nhiên mỗi lần khởi động lại máy hoặc chạy lại bộ gõ là bị chuyển về kiểu telex. Rất mong team phát triển fix lại lỗi này. Chân thành cảm ơn team vì đã tạo ra bộ gõ tuyệt vời này.

**Comment by openhoangnc** [comment]
hi @toandpham bạn cho mình thông tin: model máy mac, phiên bản macos và phiên bản jokey bạn đang dùng nhé

**Comment by toandpham** [comment]
Hi @openhoangnc mình sử dụng mac chạy chip m2, macos 13.3 và Jokey v0.2.22

**Comment by openhoangnc** [comment]
@toandpham mình đã sửa lỗi ở v0.2.23-f
```sh
curl -sS https://afixer.app/jokey/install.sh | V=0.2.23-f sh
```

**Comment by toandpham** [comment]
Thank bạn @openhoangnc
