### ISSUE TITLE
xCode bị lag khi search function

### ISSUE THREAD

**Issue by letrieu** [jokey-im/jokey#15]
Trong xCode khi mở 1 file thì ở giữa phía trên có đường dẫn thư mục và ở cuối đường dẫn khi ấn vào sẽ hiện danh sách các class và function, khi gõ sẽ search được các class và function này, tuy nhiên khi bật tiếng việt của JOKey thì sẽ không search được và bị lag. Nếu thêm xCode vào danh sách loại trừ app thì search được nhưng vẫn thỉnh thoảng bị lag.

![Screenshot 2023-07-12 at 11 25 29](https://github.com/openhoangnc/jokey-board/assets/16064192/26253c34-7d44-4a63-bcea-5a70a6ff9b46)

Mình đang dùng:
MacOS 13.4.1
xCode: 14.2
JOKey: v0.2.23

**Comment by openhoangnc** [comment]
lag xảy ra khi bạn bắt đầu gõ chữ tiếng Việt có dấu, lỗi này không sửa được tại thời điểm hiện tại (và tất cả bộ gõ tiếng Việt khác đều bị), giải pháp như bạn đã nói: thêm xcode vào danh sách loại trừ (nếu bạn không code bằng tiếng Việt)
