### ISSUE TITLE
Ghi chữ hoạch không được trên Safari

### ISSUE THREAD

**Issue by letrieu** [jokey-im/jokey#16]
Ghi chữ hoạch không được khi gõ theo kiểu telex với thứ tự sau: h o a j c h. Khi gõ như vậy thành ra chữ hạoch

**Comment by letrieu** [comment]
Tương tự với chữ ngoài: n g o a f i. Ra chữ ngàoi

**Comment by openhoangnc** [comment]
mình vẫn gõ bình thường, bạn hãy thử cập nhật phiên bản mới nhất

**Comment by letrieu** [comment]
Mới thử gõ trên app khác thì được, còn trên safari thì không. Mình dùng Notion trên safari, gõ ngay trong phần comment trang github này cũng bị

**Comment by letrieu** [comment]
Mình đang dùng bản v0.2.23

**Comment by letrieu** [comment]
Sẵn tiện thì phần tìm tin nhắn trong app Zalo mac cũng lỗi không gõ được, gõ tr thì ra chữ â

**Comment by openhoangnc** [comment]
lỗi này đã được sửa, bạn cập nhật v0.2.24 nhé
