### ISSUE TITLE
Góp ý: Bỏ dấu cân đối -> Bỏ dấu kiểu cũ (òa, òe, úy)

### ISSUE THREAD

**Issue by kandevis** [jokey-im/jokey#2]
Chào tác giả,
Mình có góp ý về ứng dụng. Hiện tại thì chức năng Bỏ dấu cân đối (sử dụng khi viết òe, òa, úy) hơi khó hiểu.
Mong tác giả có thể sửa chức năng lại thành:
1. Bỏ dấu cân đối → Đặt dấu thanh kiểu cũ (òa, òe, úy)
Hoặc
2. Đặt dấu thanh kiểu mới (oà, oè, uý)

Cảm ơn tác giả

**Comment by openhoangnc** [comment]
cảm ơn góp ý của bạn, mình sẽ cập nhật lại menu cho dễ hiểu trong phiên bản tiếp theo
