### ISSUE TITLE
Không chuyển được sang kiểu gõ VNI

### ISSUE THREAD

**Issue by zeemrx0** [jokey-im/jokey#20]
Không chuyển được sang kiểu gõ VNI

Video mô tả:
https://github.com/openhoangnc/jokey-board/assets/48668462/839987a2-27bf-47f7-9b44-b0e7b5b44b3d

**Comment by openhoangnc** [comment]
Mình mới kiểm tra, lỗi này không xảy ra trên máy mình, bạn vui lòng cung cấp thêm thông tin về phiên bản mac OS đang sử dụng.

**Comment by zeemrx0** [comment]
> Mình mới kiểm tra, lỗi này không xảy ra trên máy mình, bạn vui lòng cung cấp thêm thông tin về phiên bản mac OS đang sử dụng.

Mình sử dụng macOS Sonoma beta 6, kh biết beta bị thì sau này release có sao kh

**Comment by openhoangnc** [comment]
mình đã lên macOS 14 và đã thấy lỗi này, mình sẽ sớm fix

**Comment by openhoangnc** [comment]
@zeemrx0 mình đã sửa lỗi này ở v0.2.28
