### ISSUE TITLE
Lỗi trên app Parallels

### ISSUE THREAD

**Issue by ndthanh298** [jokey-im/jokey#22]
Dear Team,

Mỗi khi mình mở Parallels thì bộ gõ sẽ tự chuyển sang A, điều này khá bất tiện khi chuyển qua lại khi làm việc, mình đã thử trên các bộ gõ khác thì không gặp tình trạng trên, cũng thử loại trừ nhưng không hiển thị trong app dùng gần đây để loại trừ. Nhờ team hỗ trợ

**Comment by openhoangnc** [comment]
mình sẽ kiểm tra và fix bug

**Comment by openhoangnc** [comment]
Bạn không thấy trong danh sách app để loại trừ vì JOKey đã loại trừ Paralles mặc định,
mình vừa mới thử nghiệm trên Windows 11 trên Parallels® Desktop 19 for Mac và kết quả là:
- Paralles tự chuyển về bộ gõ tiếng Anh ngay khi bấm vào màn hình Windows
- Trong màn hình khác của Parallels như chỗ nhập Activation key thì gõ ra chữ bình thường (tất nhiên là không có dấu vì đã loại trừ)
<img width="333" alt="image" src="https://github.com/openhoangnc/jokey-board/assets/20717116/69286549-b8d0-4797-bc49-2af8d25c611f">

**Comment by ndthanh298** [comment]
Hiện tại khi mình vào parallels nó tự động chuyển EN, khi ở môi trường MacOS thì phải tự chuyển lại VI khá mất thời gian và bất tiện, bạn có thể gợi ý mình phương án nào cho trường hợp này không

**Comment by openhoangnc** [comment]
mình sẽ thêm tính năng tự động bật lại bộ gõ sau khi chuyển qua app khác ngoài Paralles

**Comment by openhoangnc** [comment]
@ndthanh298 mình đã thêm tính năng tự bật lại bộ gõ sau khi chuyển ra khỏi Parallels.
