### ISSUE TITLE
không gõ tiếng Việt được trên Web App của Safari 17.0, macOS 14 Sonoma

### ISSUE THREAD

**Issue by openhoangnc** [jokey-im/jokey#24]
@honghai2196 nhờ bạn comment thêm chi tiết

**Comment by kandevis** [comment]
OS version: macOS 14.0 Sonoma
OS build number: 23A344
Safari version: 17.0 (19616.1.27.211.1)
Safari WebApp version: 1.0

Tình trạng:
- Safari: bình thường
- Web app: không bỏ dấu được. Gõ dấu thì chữ vừa hiện dấu là mất ngay và chuyển thành không dấu

**Comment by openhoangnc** [comment]
@honghai2196  mình đã sửa lỗi này ở v0.2.28
