### ISSUE TITLE
Sometime got this when update

### ISSUE THREAD

**Issue by ttnghia195** [jokey-im/jokey#29]
Many times, I got this error when trying to update. Maybe there is an error with the curl, I'm trying to request by browser it still works!

![Screenshot 2023-11-26 at 22 25 48](https://github.com/openhoangnc/jokey-board/assets/19924565/8d4c2ffa-e998-4053-8d01-760c70ce6603)

**Comment by openhoangnc** [comment]
bạn hãy thử tắt VPN/Proxy/Warp/... khi chạy lệnh cài đặt/cập nhật
