### ISSUE TITLE
Lỗi không nhận bàn phím ở mac 10.15.7

### ISSUE THREAD

**Issue by nha1012** [jokey-im/jokey#3]
Cài đặt vào input source rồi nhưng bấm thì không nhận bàn phím luôn, mong tác giả xem xét

**Comment by anpham4rum** [comment]
Mình cũng bị lỗi ko nhận đủ bàn phím trên Mac Mini sử dụng bàn phím bluetooth 👍

**Comment by openhoangnc** [comment]
mình không có máy dùng macOS cũ nên không test được,
mình cũng không đặt mục tiêu hỗ trợ macOS cũ,
các bạn có thể nâng cấp lên macOS 11 để được hỗ trợ.
