### ISSUE TITLE
Lỗi phím mũi tên khi gõ trên trình duyệt và một số trình chat trên V 2.29

### ISSUE THREAD

**Issue by thanhdc1994** [jokey-im/jokey#30]
1/Khi gõ chữ tiếng Việt trên trình duyệt chrome ( thanh địa chỉ), trình duyệt sẽ đề xuất trước 1 số kết quả, khi bấm mũi tên xuống để chọn kết quả đề xuất thì không thực hiện được. 

Trên safari thì được.

2/Ngoài ra khi muốn edit text trên 1 số trình chat như Messenger, Teams hay telegram, sau khi xóa chữ muốn sửa, sửa lại và dùng mũi tên điều hướng qua chữ kế bên thì chữ cũ vừa sửa bị xóa mất.

**Đã test **V2.25** thì không bị những lỗi này, các version sau đều bị.**

Hi vọng ad sẽ khắc phục sớm

**Comment by openhoangnc** [comment]
bạn bật chế độ "Không gạch chân" theo hướng dẫn này https://afixer.app/jokey/manual/accessibility

**Comment by thanhdc1994** [comment]
cảm ơn bác, đúng là đã khắc phục được
