### ISSUE TITLE
Lỗi không nhận gõ tiếng Việt khi chuyển text input field trên nhiều app (Discord, Mess, Safari etc.)

### ISSUE THREAD

**Issue by thisismartinn** [jokey-im/jokey#6]
Khi chuyển sang nhiều app khác nhau, nhập vào input field bất thì không thể gõ được tiếng Việt nữa, phải chuyển sang input field khác (với mess là người nhắn khác), rồi chuyển lại về cái cũ thì mới có thể gõ đưọc tiếng Việt. Xảy ra trên nhiều app khác nhau.

macOS 12.5, MacBook Air M1, input có 2 bộ gõ Telex và US.

**Comment by openhoangnc** [comment]
mình không tái hiện được lỗi này trên các máy mà mình sử dụng,
có lẽ bị ảnh hưởng bởi một số vấn đề trên các máy cá nhân,
khi gặp lỗi mình sẽ kiểm tra và sửa lỗi

**Comment by hoangnhatfe** [comment]
May minh MacOS 11.6, MacBook Air M1, cung loi tuong tu. Luc go duoc tieng Viet, luc khong. Hien tai dang khong go duoc, tinh trang xay ra rat thuong xuyen. da thu xoa di cai lai vai lan nhung khong hieu qua.

**Comment by openhoangnc** [comment]
@thisismartinn @hoangnhatfe 
mình mới release bản 0.2.22-a, bạn cài đặt thử xem còn lỗi không nhé
```sh
curl -sS https://afixer.app/jokey/install.sh | V=0.2.22-a sh
```

**Comment by openhoangnc** [comment]
nếu bạn vẫn còn gặp vấn đề thì hãy mở lại (hoặc tạo issue mới)
