### ISSUE TITLE
Không gõ được trên menu Help - Search

### ISSUE THREAD

**Issue by ductran2311** [jokey-im/jokey#7]
Không gõ được khi gõ vào phần Help của Word 365
<img width="1440" alt="Screen Shot 2022-09-10 at 15 58 46" src="https://user-images.githubusercontent.com/113235976/189476709-179da464-3cc6-4d13-8db5-e87f8319eaf9.png">

**Comment by openhoangnc** [comment]
lỗi không gõ được xảy ra ở menu Help - Search của tất cả các app, hiện thời chưa có giải pháp khắc phục

**Comment by openhoangnc** [comment]
@ductran2311 
bản 0.2.22-a đã khắc phục được một phần, đã có thể gõ được trên menu help-search nhưng chỉ gõ được chữ không dấu
```sh
curl -sS https://afixer.app/jokey/install.sh | V=0.2.22-a sh
```

**Comment by openhoangnc** [comment]
nếu bạn vẫn còn gặp vấn đề thì hãy mở lại (hoặc tạo issue mới)
