### ISSUE TITLE
Unable to write in Vietnamese when updated from 0.2.20 to 0.2.21

### ISSUE THREAD

**Issue by hungptse** [jokey-im/jokey#9]
![image](https://user-images.githubusercontent.com/25200427/193501614-9956d32a-8cd6-49e1-8080-a0fa25c777d8.png)

MacOS:  Monterey 12.3.1

**Comment by openhoangnc** [comment]
I'm investigating it.
Is your Mac an Intel model?

**Comment by openhoangnc** [comment]
Please try the beta version by using this command to install
`curl -sS https://afixer.app/jokey/install-beta.sh | sh`

**Comment by hungptse** [comment]
Hello, I'm exploring an issue caused by the Zalo Desktop Application conflict with your app. Thanks for the advice.
> I'm investigating it. Is your Mac an Intel model?
Nope. It M1 model

**Comment by openhoangnc** [comment]
nếu bạn vẫn còn gặp vấn đề thì hãy mở lại (hoặc tạo issue mới)
